services:
    kurrent_db_client.event_store:
        class: KurrentDB\EventStore
        public: true
        arguments:
            - '%kurrent_db_client.base_url%'
            - '@kurrent_db_client.http_client'

    kurrent_db_client.http_client:
        class: KurrentDB\Http\GuzzleHttpClient
