language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION='2.3.*' EVENT_STORE_VERSION='v3.0.1'
  - SYMFONY_VERSION='2.4.*' EVENT_STORE_VERSION='v3.0.1'
  - SYMFONY_VERSION='2.5.*' EVENT_STORE_VERSION='v3.0.1'


before_install:
    - wget http://download.geteventstore.com/binaries/EventStore-OSS-Linux-${EVENT_STORE_VERSION}.tar.gz
    - tar xf EventStore*.tar.gz
    - cd EventStore* && ./clusternode --mem-db 2>&1> eventstore.log &

install:
    - composer require --no-update symfony/symfony=${SYMFONY_VERSION}
    - composer install --prefer-source --no-interaction

script: bin/phpunit --coverage-clover=coverage.clover --coverage-text

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_scripts:
  - killall -SIGINT clusternode
  - cat EventStore*/eventstore.log
